// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7V2Ykh7AS4-JKx_xwu-gXcnVhW5jNdo',
    appId: '1:630232213688:web:0f5c03b766d71d134a6c4d',
    messagingSenderId: '630232213688',
    projectId: 'niveusassignment',
    authDomain: 'niveusassignment.firebaseapp.com',
    storageBucket: 'niveusassignment.appspot.com',
    measurementId: 'G-S4HFF99BVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_IxKCO_UfiGx7uocZuKsr3qMfJbjCWm0',
    appId: '1:630232213688:android:e93aa30af2fcf1404a6c4d',
    messagingSenderId: '630232213688',
    projectId: 'niveusassignment',
    storageBucket: 'niveusassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1aswp2TQG9x1Yk4eA4Kv_Kwk3whhCtb0',
    appId: '1:630232213688:ios:d9fdf080d32fcd964a6c4d',
    messagingSenderId: '630232213688',
    projectId: 'niveusassignment',
    storageBucket: 'niveusassignment.appspot.com',
    iosBundleId: 'com.example.quizAppAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1aswp2TQG9x1Yk4eA4Kv_Kwk3whhCtb0',
    appId: '1:630232213688:ios:c63ddb097a595e304a6c4d',
    messagingSenderId: '630232213688',
    projectId: 'niveusassignment',
    storageBucket: 'niveusassignment.appspot.com',
    iosBundleId: 'com.example.quizAppAssignment.RunnerTests',
  );
}
